// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTourism.Data;

#nullable disable

namespace ProjectTourism.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActivityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityID"));

                    b.Property<string>("ActivityName")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("Activity_Name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("Trip_ID");

                    b.HasKey("ActivityID")
                        .HasName("ActivityID");

                    b.HasIndex("TripId");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Attraction", b =>
                {
                    b.Property<int>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Attraction_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttractionId"));

                    b.Property<string>("AttractionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Attraction_Name");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AttractionId")
                        .HasName("AttractionId");

                    b.ToTable("Attraction", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Booking_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("CostBooking")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("Trip_Id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("BookingId")
                        .HasName("PK__Booking");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Offers", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Title")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int");

                    b.HasKey("OfferId")
                        .HasName("PK__Offers");

                    b.HasIndex("TripId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Payment_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("Booking_Id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment");

                    b.HasIndex("BookingId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Review_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("Trip_Id");

                    b.HasKey("ReviewId")
                        .HasName("PK__Review");

                    b.HasIndex("TripId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TripAttraction", b =>
                {
                    b.Property<int>("TripAttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Trip_Attraction_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripAttractionId"));

                    b.Property<int?>("AttractionId")
                        .HasColumnType("int")
                        .HasColumnName("Attraction_Id");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("Trip_Id");

                    b.HasKey("TripAttractionId")
                        .HasName("PK__Trip_Att");

                    b.HasIndex("AttractionId");

                    b.HasIndex("TripId");

                    b.ToTable("Trip_Attraction", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Trips", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("TripId")
                        .HasName("PK__Trip");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("UserType")
                        .HasColumnType("bit")
                        .HasColumnName("User_Type");

                    b.HasKey("UserId")
                        .HasName("PK__Users");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Activity", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Trips", "Trips")
                        .WithMany("Activities")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK__Activity__Trip_ID");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Booking", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Trips", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK__Booking__Trip_Id");

                    b.HasOne("DataAccessLayer.Entities.Users", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Booking__User_Id");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Offers", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Trips", "Trips")
                        .WithMany("Offers")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK__Offers__Trip_Id");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__Payment__Booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Review", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Trips", "Trip")
                        .WithMany("Reviews")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK__Review__Trip_Id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TripAttraction", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Attraction", "Attraction")
                        .WithMany("TripAttraction")
                        .HasForeignKey("AttractionId")
                        .HasConstraintName("FK__Trip_Attr__Attra");

                    b.HasOne("DataAccessLayer.Entities.Trips", "Trip")
                        .WithMany("TripAttraction")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK__Trip_Attr__Trip");

                    b.Navigation("Attraction");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Attraction", b =>
                {
                    b.Navigation("TripAttraction");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Trips", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Bookings");

                    b.Navigation("Offers");

                    b.Navigation("Reviews");

                    b.Navigation("TripAttraction");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Users", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
